// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/auth/login.tsx";
import * as $2 from "./routes/auth/org.tsx";
import * as $3 from "./routes/auth/project.tsx";
import * as $4 from "./routes/auth/register.tsx";
import * as $5 from "./routes/auth/verification.tsx";
import * as $6 from "./routes/console/functions/create.tsx";
import * as $7 from "./routes/console/index.tsx";
import * as $8 from "./routes/console/logs/index.tsx";
import * as $9 from "./routes/console/secrets/index.tsx";
import * as $10 from "./routes/console/settings/index.tsx";
import * as $11 from "./routes/index.tsx";
import * as $$0 from "./islands/benefit.tsx";
import * as $$1 from "./islands/blocks.tsx";
import * as $$2 from "./islands/card.tsx";
import * as $$3 from "./islands/checkboxes.tsx";
import * as $$4 from "./islands/copyright.tsx";
import * as $$5 from "./islands/deploy.tsx";
import * as $$6 from "./islands/dropdown.tsx";
import * as $$7 from "./islands/flow-message.tsx";
import * as $$8 from "./islands/footer.tsx";
import * as $$9 from "./islands/form-auth-login.tsx";
import * as $$10 from "./islands/form-auth-register.tsx";
import * as $$11 from "./islands/form-auth-verification.tsx";
import * as $$12 from "./islands/form-multiple-select.tsx";
import * as $$13 from "./islands/form-routes-create.tsx";
import * as $$14 from "./islands/header.tsx";
import * as $$15 from "./islands/input-checkbox.tsx";
import * as $$16 from "./islands/input-file.tsx";
import * as $$17 from "./islands/navigation-items.tsx";
import * as $$18 from "./islands/notification.tsx";
import * as $$19 from "./islands/org-list.tsx";
import * as $$20 from "./islands/ory-flow.tsx";
import * as $$21 from "./islands/ory-node.tsx";
import * as $$22 from "./islands/overview-stats.tsx";
import * as $$23 from "./islands/pricing.tsx";
import * as $$24 from "./islands/settings-account.tsx";
import * as $$25 from "./islands/settings-tab.tsx";
import * as $$26 from "./islands/settings.tsx";
import * as $$27 from "./islands/switch.tsx";
import * as $$28 from "./islands/table-end-secrets.tsx";
import * as $$29 from "./islands/table-functions.tsx";
import * as $$30 from "./islands/table-logs-view.tsx";
import * as $$31 from "./islands/table-registry-secrets.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/auth/login.tsx": $1,
    "./routes/auth/org.tsx": $2,
    "./routes/auth/project.tsx": $3,
    "./routes/auth/register.tsx": $4,
    "./routes/auth/verification.tsx": $5,
    "./routes/console/functions/create.tsx": $6,
    "./routes/console/index.tsx": $7,
    "./routes/console/logs/index.tsx": $8,
    "./routes/console/secrets/index.tsx": $9,
    "./routes/console/settings/index.tsx": $10,
    "./routes/index.tsx": $11,
  },
  islands: {
    "./islands/benefit.tsx": $$0,
    "./islands/blocks.tsx": $$1,
    "./islands/card.tsx": $$2,
    "./islands/checkboxes.tsx": $$3,
    "./islands/copyright.tsx": $$4,
    "./islands/deploy.tsx": $$5,
    "./islands/dropdown.tsx": $$6,
    "./islands/flow-message.tsx": $$7,
    "./islands/footer.tsx": $$8,
    "./islands/form-auth-login.tsx": $$9,
    "./islands/form-auth-register.tsx": $$10,
    "./islands/form-auth-verification.tsx": $$11,
    "./islands/form-multiple-select.tsx": $$12,
    "./islands/form-routes-create.tsx": $$13,
    "./islands/header.tsx": $$14,
    "./islands/input-checkbox.tsx": $$15,
    "./islands/input-file.tsx": $$16,
    "./islands/navigation-items.tsx": $$17,
    "./islands/notification.tsx": $$18,
    "./islands/org-list.tsx": $$19,
    "./islands/ory-flow.tsx": $$20,
    "./islands/ory-node.tsx": $$21,
    "./islands/overview-stats.tsx": $$22,
    "./islands/pricing.tsx": $$23,
    "./islands/settings-account.tsx": $$24,
    "./islands/settings-tab.tsx": $$25,
    "./islands/settings.tsx": $$26,
    "./islands/switch.tsx": $$27,
    "./islands/table-end-secrets.tsx": $$28,
    "./islands/table-functions.tsx": $$29,
    "./islands/table-logs-view.tsx": $$30,
    "./islands/table-registry-secrets.tsx": $$31,
  },
  baseUrl: import.meta.url,
};

export default manifest;
