// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_layout.tsx";
import * as $4 from "./routes/auth/_layout.tsx";
import * as $5 from "./routes/auth/login.tsx";
import * as $6 from "./routes/auth/org.tsx";
import * as $7 from "./routes/auth/project.tsx";
import * as $8 from "./routes/auth/register.tsx";
import * as $9 from "./routes/auth/verification.tsx";
import * as $10 from "./routes/console/_layout.tsx";
import * as $11 from "./routes/console/functions/create.tsx";
import * as $12 from "./routes/console/index.tsx";
import * as $13 from "./routes/console/logs/index.tsx";
import * as $14 from "./routes/console/secrets/index.tsx";
import * as $15 from "./routes/console/settings/index.tsx";
import * as $16 from "./routes/index.tsx";
import * as $$0 from "./islands/card.tsx";
import * as $$1 from "./islands/checkboxes.tsx";
import * as $$2 from "./islands/deploy.tsx";
import * as $$3 from "./islands/dropdown.tsx";
import * as $$4 from "./islands/flow-message.tsx";
import * as $$5 from "./islands/form-auth-login.tsx";
import * as $$6 from "./islands/form-auth-register.tsx";
import * as $$7 from "./islands/form-auth-verification.tsx";
import * as $$8 from "./islands/form-multiple-select.tsx";
import * as $$9 from "./islands/form-routes-create.tsx";
import * as $$10 from "./islands/header.tsx";
import * as $$11 from "./islands/input-checkbox.tsx";
import * as $$12 from "./islands/input-file.tsx";
import * as $$13 from "./islands/navigation-items.tsx";
import * as $$14 from "./islands/ory-flow.tsx";
import * as $$15 from "./islands/pricing.tsx";
import * as $$16 from "./islands/settings-tab.tsx";
import * as $$17 from "./islands/settings.tsx";
import * as $$18 from "./islands/switch.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_layout.tsx": $3,
    "./routes/auth/_layout.tsx": $4,
    "./routes/auth/login.tsx": $5,
    "./routes/auth/org.tsx": $6,
    "./routes/auth/project.tsx": $7,
    "./routes/auth/register.tsx": $8,
    "./routes/auth/verification.tsx": $9,
    "./routes/console/_layout.tsx": $10,
    "./routes/console/functions/create.tsx": $11,
    "./routes/console/index.tsx": $12,
    "./routes/console/logs/index.tsx": $13,
    "./routes/console/secrets/index.tsx": $14,
    "./routes/console/settings/index.tsx": $15,
    "./routes/index.tsx": $16,
  },
  islands: {
    "./islands/card.tsx": $$0,
    "./islands/checkboxes.tsx": $$1,
    "./islands/deploy.tsx": $$2,
    "./islands/dropdown.tsx": $$3,
    "./islands/flow-message.tsx": $$4,
    "./islands/form-auth-login.tsx": $$5,
    "./islands/form-auth-register.tsx": $$6,
    "./islands/form-auth-verification.tsx": $$7,
    "./islands/form-multiple-select.tsx": $$8,
    "./islands/form-routes-create.tsx": $$9,
    "./islands/header.tsx": $$10,
    "./islands/input-checkbox.tsx": $$11,
    "./islands/input-file.tsx": $$12,
    "./islands/navigation-items.tsx": $$13,
    "./islands/ory-flow.tsx": $$14,
    "./islands/pricing.tsx": $$15,
    "./islands/settings-tab.tsx": $$16,
    "./islands/settings.tsx": $$17,
    "./islands/switch.tsx": $$18,
  },
  baseUrl: import.meta.url,
};

export default manifest;
