/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IdentityPatchResponse } from '../models/IdentityPatchResponse.ts';
import { HttpFile } from '../http/http.ts';

/**
* Patch identities response
*/
export class BatchPatchIdentitiesResponse {
    /**
    * The patch responses for the individual identities.
    */
    'identities'?: Array<IdentityPatchResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "identities",
            "baseName": "identities",
            "type": "Array<IdentityPatchResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchPatchIdentitiesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

