/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContinueWithVerificationUiFlow } from '../models/ContinueWithVerificationUiFlow.ts';
import { HttpFile } from '../http/http.ts';

/**
* Indicates, that the UI flow could be continued by showing a verification ui
*/
export class ContinueWithVerificationUi {
    /**
    * Action will always be `show_verification_ui` set_ory_session_token ContinueWithActionSetOrySessionToken show_verification_ui ContinueWithActionShowVerificationUI
    */
    'action': ContinueWithVerificationUiActionEnum;
    'flow': ContinueWithVerificationUiFlow;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ContinueWithVerificationUiActionEnum",
            "format": ""
        },
        {
            "name": "flow",
            "baseName": "flow",
            "type": "ContinueWithVerificationUiFlow",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContinueWithVerificationUi.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ContinueWithVerificationUiActionEnum = "set_ory_session_token" | "show_verification_ui" ;

