/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Indicates that a session was issued, and the application should use this token for authenticated requests
*/
export class ContinueWithSetOrySessionToken {
    /**
    * Action will always be `set_ory_session_token` set_ory_session_token ContinueWithActionSetOrySessionToken show_verification_ui ContinueWithActionShowVerificationUI
    */
    'action': ContinueWithSetOrySessionTokenActionEnum;
    /**
    * Token is the token of the session
    */
    'ory_session_token': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ContinueWithSetOrySessionTokenActionEnum",
            "format": ""
        },
        {
            "name": "ory_session_token",
            "baseName": "ory_session_token",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContinueWithSetOrySessionToken.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ContinueWithSetOrySessionTokenActionEnum = "set_ory_session_token" | "show_verification_ui" ;

