/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GenericError } from '../models/GenericError.ts';
import { HttpFile } from '../http/http.ts';

export class ErrorAuthenticatorAssuranceLevelNotSatisfied {
    'error'?: GenericError;
    /**
    * Points to where to redirect the user to next.
    */
    'redirect_browser_to'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "GenericError",
            "format": ""
        },
        {
            "name": "redirect_browser_to",
            "baseName": "redirect_browser_to",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ErrorAuthenticatorAssuranceLevelNotSatisfied.attributeTypeMap;
    }

    public constructor() {
    }
}

