/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class GenericError {
    /**
    * The status code
    */
    'code'?: number;
    /**
    * Debug information  This field is often not exposed to protect against leaking sensitive information.
    */
    'debug'?: string;
    /**
    * Further error details
    */
    'details'?: any;
    /**
    * The error ID  Useful when trying to identify various errors in application logic.
    */
    'id'?: string;
    /**
    * Error message  The error\'s message.
    */
    'message': string;
    /**
    * A human-readable reason for the error
    */
    'reason'?: string;
    /**
    * The request ID  The request ID is often exposed internally in order to trace errors across service architectures. This is often a UUID.
    */
    'request'?: string;
    /**
    * The status description
    */
    'status'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "debug",
            "baseName": "debug",
            "type": "string",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "any",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenericError.attributeTypeMap;
    }

    public constructor() {
    }
}

