/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Create Identity and Import Social Sign In Credentials Configuration
*/
export class IdentityWithCredentialsOidcConfigProvider {
    /**
    * The OpenID Connect provider to link the subject to. Usually something like `google` or `github`.
    */
    'provider': string;
    /**
    * The subject (`sub`) of the OpenID Connect connection. Usually the `sub` field of the ID Token.
    */
    'subject': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IdentityWithCredentialsOidcConfigProvider.attributeTypeMap;
    }

    public constructor() {
    }
}

