/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateIdentityBody } from '../models/CreateIdentityBody.ts';
import { HttpFile } from '../http/http.ts';

/**
* Payload for patching an identity
*/
export class IdentityPatch {
    'create'?: CreateIdentityBody;
    /**
    * The ID of this patch.  The patch ID is optional. If specified, the ID will be returned in the response, so consumers of this API can correlate the response with the patch.
    */
    'patch_id'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "create",
            "baseName": "create",
            "type": "CreateIdentityBody",
            "format": ""
        },
        {
            "name": "patch_id",
            "baseName": "patch_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return IdentityPatch.attributeTypeMap;
    }

    public constructor() {
    }
}

