/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* An Identity JSON Schema Container
*/
export class IdentitySchemaContainer {
    /**
    * The ID of the Identity JSON Schema
    */
    'id'?: string;
    /**
    * The actual Identity JSON Schema
    */
    'schema'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IdentitySchemaContainer.attributeTypeMap;
    }

    public constructor() {
    }
}

