/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Response for a single identity patch
*/
export class IdentityPatchResponse {
    /**
    * The action for this specific patch create ActionCreate  Create this identity.
    */
    'action'?: IdentityPatchResponseActionEnum;
    /**
    * The identity ID payload of this patch
    */
    'identity'?: string;
    /**
    * The ID of this patch response, if an ID was specified in the patch.
    */
    'patch_id'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "IdentityPatchResponseActionEnum",
            "format": ""
        },
        {
            "name": "identity",
            "baseName": "identity",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "patch_id",
            "baseName": "patch_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return IdentityPatchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type IdentityPatchResponseActionEnum = "create" ;

