/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IdentityWithCredentialsOidcConfigProvider } from '../models/IdentityWithCredentialsOidcConfigProvider.ts';
import { IdentityWithCredentialsPasswordConfig } from '../models/IdentityWithCredentialsPasswordConfig.ts';
import { HttpFile } from '../http/http.ts';

export class IdentityWithCredentialsOidcConfig {
    'config'?: IdentityWithCredentialsPasswordConfig;
    /**
    * A list of OpenID Connect Providers
    */
    'providers'?: Array<IdentityWithCredentialsOidcConfigProvider>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "IdentityWithCredentialsPasswordConfig",
            "format": ""
        },
        {
            "name": "providers",
            "baseName": "providers",
            "type": "Array<IdentityWithCredentialsOidcConfigProvider>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IdentityWithCredentialsOidcConfig.attributeTypeMap;
    }

    public constructor() {
    }
}

