/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Logout Flow
*/
export class LogoutFlow {
    /**
    * LogoutToken can be used to perform logout using AJAX.
    */
    'logout_token': string;
    /**
    * LogoutURL can be opened in a browser to sign the user out.  format: uri
    */
    'logout_url': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "logout_token",
            "baseName": "logout_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "logout_url",
            "baseName": "logout_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LogoutFlow.attributeTypeMap;
    }

    public constructor() {
    }
}

