/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IdentityPatch } from '../models/IdentityPatch.ts';
import { HttpFile } from '../http/http.ts';

/**
* Patch Identities Body
*/
export class PatchIdentitiesBody {
    /**
    * Identities holds the list of patches to apply  required
    */
    'identities'?: Array<IdentityPatch>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "identities",
            "baseName": "identities",
            "type": "Array<IdentityPatch>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatchIdentitiesBody.attributeTypeMap;
    }

    public constructor() {
    }
}

