/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Perform Native Logout Request Body
*/
export class PerformNativeLogoutBody {
    /**
    * The Session Token  Invalidate this session token.
    */
    'session_token': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "session_token",
            "baseName": "session_token",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PerformNativeLogoutBody.attributeTypeMap;
    }

    public constructor() {
    }
}

