/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Used when an administrator creates a recovery code for an identity.
*/
export class RecoveryCodeForIdentity {
    /**
    * Expires At is the timestamp of when the recovery flow expires  The timestamp when the recovery link expires.
    */
    'expires_at'?: Date;
    /**
    * RecoveryCode is the code that can be used to recover the account
    */
    'recovery_code': string;
    /**
    * RecoveryLink with flow  This link opens the recovery UI with an empty `code` field.
    */
    'recovery_link': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "expires_at",
            "baseName": "expires_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "recovery_code",
            "baseName": "recovery_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "recovery_link",
            "baseName": "recovery_link",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RecoveryCodeForIdentity.attributeTypeMap;
    }

    public constructor() {
    }
}

