/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Used when an administrator creates a recovery link for an identity.
*/
export class RecoveryLinkForIdentity {
    /**
    * Recovery Link Expires At  The timestamp when the recovery link expires.
    */
    'expires_at'?: Date;
    /**
    * Recovery Link  This link can be used to recover the account.
    */
    'recovery_link': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "expires_at",
            "baseName": "expires_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "recovery_link",
            "baseName": "recovery_link",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RecoveryLinkForIdentity.attributeTypeMap;
    }

    public constructor() {
    }
}

