/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuthenticatorAssuranceLevel } from '../models/AuthenticatorAssuranceLevel.ts';
import { HttpFile } from '../http/http.ts';

/**
* A singular authenticator used during authentication / login.
*/
export class SessionAuthenticationMethod {
    'aal'?: AuthenticatorAssuranceLevel;
    /**
    * When the authentication challenge was completed.
    */
    'completed_at'?: Date;
    'method'?: SessionAuthenticationMethodMethodEnum;
    /**
    * OIDC or SAML provider id used for authentication
    */
    'provider'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "aal",
            "baseName": "aal",
            "type": "AuthenticatorAssuranceLevel",
            "format": ""
        },
        {
            "name": "completed_at",
            "baseName": "completed_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "SessionAuthenticationMethodMethodEnum",
            "format": ""
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SessionAuthenticationMethod.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SessionAuthenticationMethodMethodEnum = "link_recovery" | "code_recovery" | "password" | "totp" | "oidc" | "webauthn" | "lookup_secret" | "v0.6_legacy_session" ;

