/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Session } from '../models/Session.ts';
import { HttpFile } from '../http/http.ts';

/**
* The Response for Registration Flows via API
*/
export class SuccessfulCodeExchangeResponse {
    'session': Session;
    /**
    * The Session Token  A session token is equivalent to a session cookie, but it can be sent in the HTTP Authorization Header:  Authorization: bearer ${session-token}  The session token is only issued for API flows, not for Browser flows!
    */
    'session_token'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "session",
            "baseName": "session",
            "type": "Session",
            "format": ""
        },
        {
            "name": "session_token",
            "baseName": "session_token",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuccessfulCodeExchangeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

