/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UiNodeAttributes } from '../models/UiNodeAttributes.ts';
import { UiNodeMeta } from '../models/UiNodeMeta.ts';
import { UiText } from '../models/UiText.ts';
import { HttpFile } from '../http/http.ts';

/**
* Nodes are represented as HTML elements or their native UI equivalents. For example, a node can be an `<img>` tag, or an `<input element>` but also `some plain text`.
*/
export class UiNode {
    'attributes': UiNodeAttributes;
    /**
    * Group specifies which group (e.g. password authenticator) this node belongs to. default DefaultGroup password PasswordGroup oidc OpenIDConnectGroup profile ProfileGroup link LinkGroup code CodeGroup totp TOTPGroup lookup_secret LookupGroup webauthn WebAuthnGroup
    */
    'group': UiNodeGroupEnum;
    'messages': Array<UiText>;
    'meta': UiNodeMeta;
    /**
    * The node\'s type text Text input Input img Image a Anchor script Script
    */
    'type': UiNodeTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "UiNodeAttributes",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "UiNodeGroupEnum",
            "format": ""
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<UiText>",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "UiNodeMeta",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UiNodeTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UiNode.attributeTypeMap;
    }

    public constructor() {
    }
}


export type UiNodeGroupEnum = "default" | "password" | "oidc" | "profile" | "link" | "code" | "totp" | "lookup_secret" | "webauthn" ;
export type UiNodeTypeEnum = "text" | "input" | "img" | "a" | "script" ;

