/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IdentityState } from '../models/IdentityState.ts';
import { IdentityWithCredentials } from '../models/IdentityWithCredentials.ts';
import { HttpFile } from '../http/http.ts';

/**
* Update Identity Body
*/
export class UpdateIdentityBody {
    'credentials'?: IdentityWithCredentials;
    /**
    * Store metadata about the user which is only accessible through admin APIs such as `GET /admin/identities/<id>`.
    */
    'metadata_admin'?: any | null;
    /**
    * Store metadata about the identity which the identity itself can see when calling for example the session endpoint. Do not store sensitive information (e.g. credit score) about the identity in this field.
    */
    'metadata_public'?: any | null;
    /**
    * SchemaID is the ID of the JSON Schema to be used for validating the identity\'s traits. If set will update the Identity\'s SchemaID.
    */
    'schema_id': string;
    'state': IdentityState;
    /**
    * Traits represent an identity\'s traits. The identity is able to create, modify, and delete traits in a self-service manner. The input will always be validated against the JSON Schema defined in `schema_id`.
    */
    'traits': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "IdentityWithCredentials",
            "format": ""
        },
        {
            "name": "metadata_admin",
            "baseName": "metadata_admin",
            "type": "any",
            "format": ""
        },
        {
            "name": "metadata_public",
            "baseName": "metadata_public",
            "type": "any",
            "format": ""
        },
        {
            "name": "schema_id",
            "baseName": "schema_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "IdentityState",
            "format": ""
        },
        {
            "name": "traits",
            "baseName": "traits",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateIdentityBody.attributeTypeMap;
    }

    public constructor() {
    }
}



