/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Update Registration Flow with Password Method
*/
export class UpdateRegistrationFlowWithPasswordMethod {
    /**
    * The CSRF Token
    */
    'csrf_token'?: string;
    /**
    * Method to use  This field must be set to `password` when using the password method.
    */
    'method': string;
    /**
    * Password to sign the user up with
    */
    'password': string;
    /**
    * The identity\'s traits
    */
    'traits': any;
    /**
    * Transient data to pass along to any webhooks
    */
    'transient_payload'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "csrf_token",
            "baseName": "csrf_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "traits",
            "baseName": "traits",
            "type": "any",
            "format": ""
        },
        {
            "name": "transient_payload",
            "baseName": "transient_payload",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateRegistrationFlowWithPasswordMethod.attributeTypeMap;
    }

    public constructor() {
    }
}

