/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * OpenAPI spec version: 
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* VerifiableAddress is an identity\'s verifiable address
*/
export class VerifiableIdentityAddress {
    /**
    * When this entry was created
    */
    'created_at'?: Date;
    /**
    * The ID
    */
    'id'?: string;
    /**
    * VerifiableAddressStatus must not exceed 16 characters as that is the limitation in the SQL Schema
    */
    'status': string;
    /**
    * When this entry was last updated
    */
    'updated_at'?: Date;
    /**
    * The address value  example foo@user.com
    */
    'value': string;
    /**
    * Indicates if the address has already been verified
    */
    'verified': boolean;
    'verified_at'?: Date;
    /**
    * VerifiableAddressType must not exceed 16 characters as that is the limitation in the SQL Schema
    */
    'via': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "verified_at",
            "baseName": "verified_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "via",
            "baseName": "via",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VerifiableIdentityAddress.attributeTypeMap;
    }

    public constructor() {
    }
}

